require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false 

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Naming/VariableNumber:
  Enabled: false